api/urls.py
from django.db import router
from django.urls import path

from api.views import (
    ArquivoViewSet,
    DocumentoViewSet,
    CacifoViewSet,
    SeccaoViewSet
)
from rest_framework.routers import DefaultRouter

app_name = 'api'
router = DefaultRouter()
router.register(r'arquivo', ArquivoViewSet, basename='arquivo')
router.register(r'documentos', DocumentoViewSet, basename='documentos')
router.register(r'cacifo', CacifoViewSet, basename='cacifo')
router.register(r'seccao', SeccaoViewSet, basename='seccao')



urlpatterns = router.urls

sged/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from sged import settings

from .views import main

urlpatterns = [
    path('', main, name = 'home'),
    path('user/', include('users.urls', namespace='user')),
    path('sistema/', include('sistema.urls', namespace='sistema')),
    path('api/', include('api.urls', namespace='api')),
    path('admin/', admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistema/urls.py
from django.urls import path


from sistema.views import ArquivoAtualizar, ArquivoCadastrar, ArquivoHome, ArquivoRemover, DocAtualizar, DocCadastrar, DocHome, DocRemover, CaçifoAtualizar, CaçifoCadastrar, CaçifoDetail, CaçifoHome, CaçifoRemover, SecçãoDetail, SeçãoAtualizar, SeçãoCadastrar, SeçãoHome, SeçãoRemover

app_name = 'sistema'
urlpatterns = [
    #Seccoes
    path('', SeçãoHome, name='home'),
    path('registar-seção/', SeçãoCadastrar, name='registar'),
    path('atualizar-secção/<str:pk>/', SeçãoAtualizar, name='atualizar-secção'),
    path('delete-secção/<str:pk>/', SeçãoRemover, name='delete-secção'),
    path('secção/<str:pk>/', SecçãoDetail, name='secção'),


    #Caçifos
    path('home-caçifo/', CaçifoHome, name='caçifo'),
    path('registar-caçifo', CaçifoCadastrar, name='registar-caçifo'),
    path('atualizar-caçifo/<str:pk>/', CaçifoAtualizar, name='atualizar-caçifo'),
    path('delete-caçifo/<str:pk>/', CaçifoRemover, name='delete-caçifo'),
    path('caçifo/<str:pk>/', CaçifoDetail, name='caçifo-detail'),

    #Arquivos
    path('home-arquivo/', ArquivoHome, name='arquivos'),
    path('registar-arquivo', ArquivoCadastrar, name='registar-arquivo'),
    path('atualizar-arquivo/<str:pk>/', ArquivoAtualizar, name='atualizar-arquivo'),
    path('delete-arquivo/<str:pk>/', ArquivoRemover, name='delete-arquivo'),

    #Docs
    path('home-docs/<codename>/', DocHome, name='docs'),
    path('registar-doc/<str:pk>/', DocCadastrar, name='registar-doc'),
    path('atualizar-doc/<str:pk>/', DocAtualizar, name='atualizar-doc'),
    path('delete-doc/<str:pk>/', DocRemover, name='delete-doc'),
]

sistema/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Secção(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1)
    codename = models.CharField(max_length=10, unique=True)
    descrição = models.CharField(max_length=150, blank=True)
    modificador = models.CharField(max_length=150)
    criado = models.DateField(auto_now_add=True)
    atualizado = models.DateField(auto_now=True)

    def __str__(self):
        return self.codename

    class Meta:
        verbose_name_plural = 'Secções'

class Caçifo(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1)
    codename = models.CharField(max_length=10, unique=True, editable=False)
    descrição = models.CharField(max_length=150, blank=True)
    secção = models.ForeignKey(Secção, on_delete=models.CASCADE)
    modificador = models.CharField(max_length=150)
    criado = models.DateField(auto_now_add=True)
    atualizado = models.DateField(auto_now=True)

    def __str__(self):
        return self.codename

    class Meta:
        verbose_name_plural = 'Caçifos'

class Arquivo(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1)
    codename = models.CharField(max_length=10, unique=True, editable=False)
    descrição = models.CharField(max_length=150, blank=True)
    caçifo = models.ForeignKey(Caçifo, on_delete=models.CASCADE)
    modificador = models.CharField(max_length=150)
    criado = models.DateField(auto_now_add=True)
    atualizado = models.DateField(auto_now=True)

    def __str__(self):
        return self.codename
    
    class Meta:
        verbose_name_plural = 'Arquivos'

class Documento(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1)
    nome = models.CharField(max_length=200, unique=True)
    file = models.FileField(max_length=200, null=True, upload_to='documents/%d/%m/%Y')
    arquivo = models.ForeignKey(Arquivo, on_delete=models.CASCADE)
    modificador = models.CharField(max_length=150)
    adicionado = models.DateField(auto_now_add=True)
    atualizado = models.DateField(auto_now=True)

    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name_plural = 'Documentos'
    

sistema/forms.py
from django import forms

from sistema.models import Arquivo, Documento, Caçifo, Secção

class BaseForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class SecçãoForm(BaseForm, forms.ModelForm):
    class Meta:
        model = Secção
        exclude = ('usuario','modificador')

class CaçifoForm(BaseForm, forms.ModelForm):
    class Meta:
        model = Caçifo
        exclude = ('usuario','modificador')

class ArquivoForm(BaseForm, forms.ModelForm):
    class Meta:
        model = Arquivo
        exclude = ('usuario','modificador')

class DocumentoForm(BaseForm, forms.ModelForm):
    class Meta:
        model = Documento
        exclude = ('usuario','modificador')

sistema/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required

from sistema.forms import ArquivoForm, DocumentoForm, CaçifoForm, SecçãoForm

from sistema.models import Arquivo, Documento, Caçifo, Secção

from sged.decorators import usuariosAutorizados

# Create your views here.
@login_required
@usuariosAutorizados(allowed_roles=['gestor', 'admin'])
def SeçãoHome(request):
    secção = Secção.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(secção, 3)
    
    try:
        secções = paginator.page(page)
    except PageNotAnInteger:
        secções = paginator.page(1)
    except EmptyPage:
        secções = paginator.page(paginator.num_pages())

    context = {'secções': secções}
    return render(request, 'seccao/home.html', context)

@login_required
@usuariosAutorizados(allowed_roles=['gestor', 'admin'])
def SeçãoCadastrar(request):
    form = SecçãoForm()
    if request.method == 'POST':
        form = SecçãoForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.usuario = request.user
            obj.save()
            return redirect('sistema:home')
    context = {'form': form}
    return render(request, 'seccao/registar.html', context)

@login_required
@usuariosAutorizados(allowed_roles=['gestor', 'admin'])
def SeçãoAtualizar(request, pk):
    secção = Secção.objects.get(id=pk)

    context = {}
    form = SecçãoForm(instance=secção)
    if request.method == 'POST':
        form = SecçãoForm(request.POST, instance=secção)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.modificador = request.user.username
            obj.save()

            return redirect('sistema:home')
    
    context['form'] = form

    return render(request, 'seccao/registar.html', context)

@login_required
@usuariosAutorizados(allowed_roles=['gestor', 'admin'])
def SeçãoRemover(request, pk):
    secção = Secção.objects.get(id=pk)

    if request.method == 'POST':
        secção.delete()
        return redirect('sistema:home')
    
    context = {'secção': secção}
    return render(request, 'seccao/delete.html', context)

@login_required
@usuariosAutorizados(allowed_roles=['gestor', 'admin'])
def SecçãoDetail(request, pk):
    secção = Secção.objects.get(id=pk)
    caçifo = Caçifo.objects.filter(secção = secção)

    page = request.GET.get('page', 1)
    paginator = Paginator(caçifo, 4)
    
    try:
        caçifos = paginator.page(page)
    except PageNotAnInteger:
        caçifos = paginator.page(1)
    except EmptyPage:
        caçifos = paginator.page(paginator.num_pages())

    context = {
        'secção':secção,
        'caçifos':caçifos
    }

    return render(request, 'seccao/seccao-details.html', context)

# Caçifo views
@login_required
@usuariosAutorizados(allowed_roles=['gestor', 'admin'])
def CaçifoHome(request):
    caçifo = Caçifo.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(caçifo, 5)
    
    try:
        caçifos = paginator.page(page)
    except PageNotAnInteger:
        caçifos = paginator.page(1)
    except EmptyPage:
        caçifos = paginator.page(paginator.num_pages())

    context = {'caçifos': caçifos}
    return render(request, 'caçifo/home.html', context)

@login_required
@usuariosAutorizados(allowed_roles=['gestor', 'admin'])
def CaçifoCadastrar(request):
    form = CaçifoForm()
    
    if request.method == 'POST':
        form = CaçifoForm(request.POST)
        secção = Secção.objects.get(id=int(form.data['secção']))
        caçifo = Caçifo.objects.all().filter(secção = secção).__len__()
        if form.is_valid():
            obj = form.save(commit=False)
            obj.usuario = request.user
            obj.codename = f'{secção.codename}{caçifo + 1}-{obj.descrição.replace(" ","").lower()}'
            obj.save()
            return redirect('sistema:caçifo')
    context = {'form': form}
    return render(request, 'caçifo/registar.html', context)

@login_required
@usuariosAutorizados(allowed_roles=['gestor', 'admin'])
def CaçifoAtualizar(request, pk):
    caçifo = Caçifo.objects.get(id=pk)

    context = {}
    form = CaçifoForm(instance=caçifo)
    if request.method == 'POST':
        form = CaçifoForm(request.POST, instance=caçifo)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.modificador = request.user.username
            obj.save()
            return redirect('sistema:caçifo')
    
    context['form'] = form

    return render(request, 'caçifo/registar.html', context)

@login_required
@usuariosAutorizados(allowed_roles=['gestor', 'admin'])
def CaçifoRemover(request, pk):
    caçifo = Caçifo.objects.get(id=pk)

    if request.method == 'POST':
        caçifo.delete()
        return redirect('sistema:caçifo')
    
    context = {'caçifo': caçifo}
    return render(request, 'caçifo/delete.html', context)

@login_required
@usuariosAutorizados(allowed_roles=['gestor', 'admin'])
def CaçifoDetail(request, pk):
    caçifo = Caçifo.objects.get(id=pk)
    arquivo = Arquivo.objects.filter(caçifo = caçifo)

    page = request.GET.get('page', 1)
    paginator = Paginator(arquivo, 4)
    
    try:
        arquivos = paginator.page(page)
    except PageNotAnInteger:
        arquivos = paginator.page(1)
    except EmptyPage:
        arquivos = paginator.page(paginator.num_pages())

    context = {
        'caçifo':caçifo,
        'arquivos':arquivos
    }

    return render(request, 'caçifo/caçifo-detail.html', context)

# Arquivo Views
@login_required
def ArquivoHome(request):
    arquivo = Arquivo.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(arquivo, 5)
    
    try:
        arquivos = paginator.page(page)
    except PageNotAnInteger:
        arquivos = paginator.page(1)
    except EmptyPage:
        arquivos = paginator.page(paginator.num_pages())

    context = {'arquivos': arquivos}
    return render(request, 'arquivo/home.html', context)

@login_required
def ArquivoCadastrar(request):
    form = ArquivoForm()
    if request.method == 'POST':
        form = ArquivoForm(request.POST)
        caçifo = Caçifo.objects.get(id=int(form.data['caçifo']))
        
        if form.is_valid():
            obj = form.save(commit=False)
            obj.usuario = request.user
            
            obj.codename = f'{caçifo.codename}-{obj.descrição}'
            
            obj.save()
            return redirect('sistema:arquivos')
    context = {'form': form}
    return render(request, 'arquivo/registar.html', context)

@login_required
def ArquivoAtualizar(request, pk):
    arquivo = Arquivo.objects.get(id=pk)

    context = {}
    form = ArquivoForm(instance=arquivo)
    if request.method == 'POST':
        form = ArquivoForm(request.POST, instance=arquivo)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.modificador = request.user.username
            obj.save()
            return redirect('sistema:arquivos')
        
    context['form'] = form

    return render(request, 'arquivo/registar.html', context)

@login_required
def ArquivoRemover(request, pk):
    arquivo = Arquivo.objects.get(id=pk)

    if request.method == 'POST':
        arquivo.delete()
        return redirect('sistema:arquivos')
    context = {'arquivo': arquivo}
    return render(request, 'arquivo/delete.html', context)

# Doc views
@login_required
def DocHome(request, codename):
    ar = Arquivo.objects.get(codename=codename)
    doc = Documento.objects.all().filter(arquivo = ar)
    
    page = request.GET.get('page', 1)
    paginator = Paginator(doc, 5)
    
    try:
        docs = paginator.page(page)
    except PageNotAnInteger:
        docs = paginator.page(1)
    except EmptyPage:
        docs = paginator.page(paginator.num_pages())

    context = {'docs': docs, 'arquivo': ar}
    return render(request, 'doc/home.html', context)

@login_required
def DocCadastrar(request, pk):
    arquivo = Arquivo.objects.get(id=pk)
    if request.method == 'GET':
        form = DocumentoForm(request.GET or None)
       
        data = {
            'arquivo': arquivo
        }
        form = DocumentoForm(initial=data)
    elif request.method == 'POST':
        form = DocumentoForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.usuario = request.user
            obj.save()
            return redirect('sistema:docs', arquivo.codename)
    else:
        form = DocumentoForm()
    context = {'form': form}
    return render(request, 'doc/registar.html', context)

@login_required
def DocAtualizar(request, pk):
    doc = Documento.objects.get(id=pk)

    context = {}
    form = DocumentoForm(instance=doc)
    if request.method == 'POST':
        form = DocumentoForm(request.POST, instance=doc)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.modificador = request.user.username
            obj.save()
            return redirect('sistema:docs', doc.arquivo.codename)
        
    context['form'] = form

    return render(request, 'arquivo/registar.html', context)

@login_required
def DocRemover(request, pk):
    documento = Documento.objects.get(id=pk)

    if request.method == 'POST':
        documento.delete()
        return redirect('sistema:docs', documento.arquivo.codename)
    context = {'documento': documento}
    return render(request, 'doc/delete.html', context)

sistema/templates/seccao/delete.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="h6 modal-title">Confirme a sua ação</h2>
                <a type="button" class="btn-close" data-bs-dismiss="modal"
                    aria-label="Close" href="{% url 'sistema:home' %}"></a>
            </div>
            <div class="modal-body">
                <h3>Tem certeza de que deseja apagar?</h3>

                <p> <b>{{ secção }}</b></p>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-secondary">Sim</button>
                <a type="button" class="btn btn-link text-gray-600 ms-auto"
                data-bs-dismiss="modal" href="{% url 'sistema:home' %}">Não</a>
            </div>
        </div>
    </div>
</form>

{% endblock content %}

sistema/templates/seccao/home.html
{% extends "base.html" %}

{% block title %}
  Seção Home
{% endblock title %}

{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap
    align-items-center py-4">
    <div class="d-block mb-4 mb-md-0">
        <h2 class="h4">Secções disponiveis</h2>
    </div>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a href="{% url 'sistema:registar' %}" class="btn btn-sm btn-outline-primary d-inline-flex
            align-items-center">
            <svg class="icon icon-xs me-2" fill="none" stroke="currentColor"
                viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path
                    stroke-linecap="round" stroke-linejoin="round"
                    stroke-width="2"
                    d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
            Nova secção
        </a>
    </div>
    </div>
    <div class="table-settings mb-4">
        <div class="row align-items-center justify-content-between">
            <div class="col col-md-6 col-lg-3 col-xl-4">
                <div class="input-group me-2 me-lg-3 fmxw-400">
                    
                </div>
            </div>
        </div>
    </div>
    <div class="card card-body border-0 shadow table-wrapper
        table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="border-gray-200">Nome da Secção</th>
                    <th class="border-gray-200">Descrição</th>
                    <th class="border-gray-200">Criado em</th>
                    <th class="border-gray-200">Atualizado em</th>
                    <th class="border-gray-200">Registado por</th>
                    <th class="border-gray-200">Atualizado por</th>
                    <th class="border-gray-200"></th>
                </tr>
            </thead>
            <tbody>
                <!-- Item -->
                {% if secções %}
                {% for seção in secções %}
                <tr>
                    <td>
                        <span class="fw-normal">{{seção.codename}}</span>
                    </td>
                    <td><span class="fw-normal">{{seção.descrição}}</span></td>
                    <td><span class="fw-normal">{{seção.criado}}</span></td>
                    <td><span class="fw-normal">{{seção.atualizado}}</span></td>
                    <td><span class="fw-normal">{{seção.usuario}}</span></td>
                    <td><span class="fw-normal">{{seção.modificador}}</span></td>
                    
                    <td>
                        <div style="display: inline-flex;">
                            <a class="text-secondary" href="{% url 'sistema:secção' seção.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" 
                                    fill="currentColor" class="bi bi-eye" viewBox="0 0 20 20">
                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173
                                     8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12
                                    0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 
                                    8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 
                                    11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 
                                    13.134 0 0 1 1.172 8z"/>
                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0
                                     1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                                  </svg>
                            </a>
                        </div>
                        <div style="display: inline-flex;">
                            <a class="text-primary" href="{% url 'sistema:atualizar-secção' seção.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" 
                                fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 20 20">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5
                                     0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 
                                     0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 
                                     .196-.12l6.813-6.814z"/>
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5
                                     0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 
                                     1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                </svg>
                            </a>
                        </div>
                        <div style="display: inline-flex;">
                            <a class="text-danger" href="{% url 'sistema:delete-secção' seção.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" 
                                fill="currentColor" class="bi bi-trash" viewBox="0 0 20 20">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5
                                     0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0
                                      1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 
                                    1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 
                                    0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5
                                     3V2h11v1h-11z"/>
                                </svg>
                            </a>
                        </div> 
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                <td colspan="7" style="text-align: center;"><span class="fw-normal text-warning">Nenhum registo encontrado! </span></td>
                {% endif %}
                
            </tbody>
        </table>
        <div class="card-footer px-3 border-0 d-flex flex-column flex-lg-row
            align-items-center justify-content-between">
            <nav aria-label="Page navigation example">
                <ul class="pagination mb-0">
                    {% if secções.has_previous %}
                      <li class="page-item">
                        <a class="page-link" href="?page={{ secções.previous_page_number }}" 
                        tabindex="-1">‹</a>
                      </li>
                    {% else %}
                      <li class="page-item disabled"><a class="page-link">‹</a></li>
                    {% endif %}
    
                    {% for i in secções.paginator.page_range %}
                      {% if secções.number == i %}
                        <li class="page-item active"><a class="page-link">{{ i }}</a></li>
                      {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                      {% endif %}
                    {% endfor %}
    
                    {% if secções.has_next %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ secções.next_page_number }}">›</a>
                    </li>
                    {% else %}
                      <li class="page-item disabled"><a class="page-link">›</a></li>
                    {% endif %}
                </ul>
            </nav>
            
            <div class="fw-normal small mt-4 mt-lg-0">A mostrar <b>{{secções.number}}</b> de <b>{{secções.paginator.num_pages}}</b>
                paginas
            </div>
        </div>
    </div>
{% endblock %}

sistema/templates/seccao/registar.html
{% extends "base.html" %}

{% block title %}
  Registar Secção
{% endblock title %}

{% block content %}
<br>
<div class="row">
    <div class="col-12 col-xl-8">
        <div class="card card-body border-0 shadow mb-4">
            <h2 class="h5 mb-4">Registro de Secção</h2>
            <form method="post" action="">
                {% csrf_token %}
                <div class="row">
                    {% for field in form %}
                    <div class="col-md-6 mb-3">
                        <div>
                            <label for="first_name">{{field.label}}</label>
                            {{field}}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="mt-3">
                    <button class="btn btn-outline-success mt-2 animate-up-2"
                      type="submit">Gravar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}