api/urls.py
from django.db import router
from django.urls import path

from api.views import (
    ArquivoViewSet,
    DocumentoViewSet,
    CacifoViewSet,
    SeccaoViewSet
)
from rest_framework.routers import DefaultRouter

app_name = 'api'
router = DefaultRouter()
router.register(r'arquivo', ArquivoViewSet, basename='arquivo')
router.register(r'documentos', DocumentoViewSet, basename='documentos')
router.register(r'cacifo', CacifoViewSet, basename='cacifo')
router.register(r'seccao', SeccaoViewSet, basename='seccao')



urlpatterns = router.urls

sged/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from sged import settings

from .views import main

urlpatterns = [
    path('', main, name = 'home'),
    path('user/', include('users.urls', namespace='user')),
    path('sistema/', include('sistema.urls', namespace='sistema')),
    path('api/', include('api.urls', namespace='api')),
    path('admin/', admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistema/urls.py
from django.urls import path


from sistema.views import ArquivoAtualizar, ArquivoCadastrar, ArquivoHome, ArquivoRemover, DocAtualizar, DocCadastrar, DocHome, DocRemover, CaçifoAtualizar, CaçifoCadastrar, CaçifoDetail, CaçifoHome, CaçifoRemover, SecçãoDetail, SeçãoAtualizar, SeçãoCadastrar, SeçãoHome, SeçãoRemover

app_name = 'sistema'
urlpatterns = [
    #Seccoes
    path('', SeçãoHome, name='home'),
    path('registar-seção/', SeçãoCadastrar, name='registar'),
    path('atualizar-secção/<str:pk>/', SeçãoAtualizar, name='atualizar-secção'),
    path('delete-secção/<str:pk>/', SeçãoRemover, name='delete-secção'),
    path('secção/<str:pk>/', SecçãoDetail, name='secção'),


    #Caçifos
    path('home-caçifo/', CaçifoHome, name='caçifo'),
    path('registar-caçifo', CaçifoCadastrar, name='registar-caçifo'),
    path('atualizar-caçifo/<str:pk>/', CaçifoAtualizar, name='atualizar-caçifo'),
    path('delete-caçifo/<str:pk>/', CaçifoRemover, name='delete-caçifo'),
    path('caçifo/<str:pk>/', CaçifoDetail, name='caçifo-detail'),

    #Arquivos
    path('home-arquivo/', ArquivoHome, name='arquivos'),
    path('registar-arquivo', ArquivoCadastrar, name='registar-arquivo'),
    path('atualizar-arquivo/<str:pk>/', ArquivoAtualizar, name='atualizar-arquivo'),
    path('delete-arquivo/<str:pk>/', ArquivoRemover, name='delete-arquivo'),

    #Docs
    path('home-docs/<codename>/', DocHome, name='docs'),
    path('registar-doc/<str:pk>/', DocCadastrar, name='registar-doc'),
    path('atualizar-doc/<str:pk>/', DocAtualizar, name='atualizar-doc'),
    path('delete-doc/<str:pk>/', DocRemover, name='delete-doc'),
]

users/urls.py
from django.contrib import auth
from django.urls import path

from django.contrib.auth import views
from users.forms import UserChangePassword

from users.views import userLogin, userLogout


app_name = 'user'
urlpatterns = [
    path('entrar/', userLogin, name='entrar'),
    path('sair/', userLogout, name='sair'),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>
      {% block title %}
        
      {% endblock title %}
    </title>
  </head>
  <body>
    <div class="container-md">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div style="float:inline-start; padding-left: 5px;">
          <a href="{% url 'home' %}" style="text-decoration: none;">
            <h1 style="text-align: right; color:aqua;">SGED</h1>
          </a>
        </div>
        <div class="container-fluid" style="padding-left: 25%;">
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item" style = "padding: 5px;">
                {% url 'home' as url %}
                {% if request.path == url %}
                  <a class="nav-link active" aria-current="page" href="{% url 'home' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="75" height="75" 
                    fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 
                      .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5
                      1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                      <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647
                      6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293
                      1.5z"/>
                    </svg>
                  </a>
                {% else %}
                <a class="nav-link" href="{% url 'home' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="75" height="75" 
                  fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 
                    .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5
                    1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                    <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647
                    6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293
                    1.5z"/>
                  </svg>
                </a>
                {% endif %}
              </li>
              <li class="nav-item" style = "padding: 5px;">
                {% url 'sistema:arquivos' as url1 %}
                {% if request.path == url1 %}
                  <a class="nav-link active" aria-current="page" href="{% url 'sistema:arquivos' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="75" height="75" 
                    fill="currentColor" class="bi bi-folder" viewBox="0 0 16 16">
                      <path d="M.54 3.87.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 
                      2 0 0 0 9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 
                      14H2.826a2 2 0 0 1-1.991-1.819l-.637-7a1.99 1.99 0 0 1 .342-1.31zM2.19 
                      4a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91h10.348a1 1 0 0 0 
                      .995-.91l.637-7A1 1 0 0 0 13.81 4H2.19zm4.69-1.707A1 1 0 0 0 6.172 2H2.5a1
                      1 0 0 0-1 .981l.006.139C1.72 3.042 1.95 3 2.19 3h5.396l-.707-.707z"/>
                    </svg>
                  </a>
                {% else %}
                  <a class="nav-link" href="{% url 'sistema:arquivos' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="75" height="75" 
                    fill="currentColor" class="bi bi-folder" viewBox="0 0 16 16">
                      <path d="M.54 3.87.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 
                      2 0 0 0 9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 
                      14H2.826a2 2 0 0 1-1.991-1.819l-.637-7a1.99 1.99 0 0 1 .342-1.31zM2.19 
                      4a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91h10.348a1 1 0 0 0 
                      .995-.91l.637-7A1 1 0 0 0 13.81 4H2.19zm4.69-1.707A1 1 0 0 0 6.172 2H2.5a1
                      1 0 0 0-1 .981l.006.139C1.72 3.042 1.95 3 2.19 3h5.396l-.707-.707z"/>
                    </svg>
                  </a>
                {% endif %}
              </li>
              {% if user.groups.all.0.name  == 'admin' or user.groups.all.0.name == 'gestor' %}
              <li class="nav-item" style = "padding: 5px;">
                {% url 'sistema:caçifo' as url2 %}
                {% if request.path == url2 %}
                  <a class="nav-link active" aria-current="page" href="{% url 'sistema:caçifo' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="75" height="75" 
                    fill="currentColor" class="bi bi-stack" viewBox="0 0 16 16">
                      <path d="m14.12 10.163 1.715.858c.22.11.22.424 0 .534L8.267
                      15.34a.598.598 0 0 1-.534 0L.165 11.555a.299.299 0 0 1 0-.534l1.716-.858 
                      5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.66zM7.733.063a.598.598 0 0 
                      1 .534 0l7.568 3.784a.3.3 0 0 1 0 .535L8.267 8.165a.598.598 0 0 1-.534 0L.165
                        4.382a.299.299 0 0 1 0-.535L7.733.063z"/>
                      <path d="m14.12 6.576 1.715.858c.22.11.22.424 0 .534l-7.568 3.784a.598.598 0 
                      0 1-.534 0L.165 7.968a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 
                      1.1.252 1.604 0l5.317-2.659z"/>
                    </svg>
                  </a>
                {% else %}
                  <a class="nav-link" href="{% url 'sistema:caçifo' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="75" height="75" 
                    fill="currentColor" class="bi bi-stack" viewBox="0 0 16 16">
                      <path d="m14.12 10.163 1.715.858c.22.11.22.424 0 .534L8.267
                      15.34a.598.598 0 0 1-.534 0L.165 11.555a.299.299 0 0 1 0-.534l1.716-.858 
                      5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.66zM7.733.063a.598.598 0 0 
                      1 .534 0l7.568 3.784a.3.3 0 0 1 0 .535L8.267 8.165a.598.598 0 0 1-.534 0L.165
                        4.382a.299.299 0 0 1 0-.535L7.733.063z"/>
                      <path d="m14.12 6.576 1.715.858c.22.11.22.424 0 .534l-7.568 3.784a.598.598 0 
                      0 1-.534 0L.165 7.968a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 
                      1.1.252 1.604 0l5.317-2.659z"/>
                    </svg>
                  </a>
                {% endif %}
              </li>
              
              <li class="nav-item" style = "padding: 5px;">
                {% url 'sistema:home' as url3 %}
                {% if request.path == url3 %}
                  <a class="nav-link active" aria-current="page" href="{% url 'sistema:home' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="75" height="75" 
                    fill="currentColor" class="bi bi-building" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 
                      0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0
                      1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5
                        0 0 1 .487.022zM6 8.694 1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 
                        .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z"/>
                      <path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 
                      0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 
                      0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 
                      0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 
                      0h1v1h-1V5zm0-2h1v1h-1V3z"/>
                    </svg>
                  </a>
                {% else %}
                  <a class="nav-link" href="{% url 'sistema:home' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="75" height="75" 
                    fill="currentColor" class="bi bi-building" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 
                      0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0
                      1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5
                        0 0 1 .487.022zM6 8.694 1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 
                        .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z"/>
                      <path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 
                      0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 
                      0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 
                      0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 
                      0h1v1h-1V5zm0-2h1v1h-1V3z"/>
                    </svg>
                  </a>
                {% endif %}
                
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
        <div style="float: inline-start; width: 200px">
          <b>
            <span class="text-sm" style="font-size: 6pt;">Entrou como:</span>
          </b>
         
          <span class="text-sm" style="font-size: 6pt;">
            {% if user.get_full_name %}
              {{ user.get_full_name|upper }}
            {% else %}
              {{ user|upper }}
            {% endif %}
          </span>
        </div>
        <div class="dropdown" style="float: inline-end;">
          <button class="btn" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="65" height="65" fill="currentColor" 
            class="bi bi-person-circle" viewBox="0 0 16 16">
              <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
              <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 
              11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
            </svg>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item text-danger" href="{% url 'user:sair' %}">
              Sair
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-down" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M3.5 10a.5.5 0 0 1-.5-.5v-8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 0 0 1h2A1.5 1.5 0 0 0 14 9.5v-8A1.5 1.5 0 0 0 12.5 0h-9A1.5 1.5 0 0 0 2 1.5v8A1.5 1.5 0 0 0 3.5 11h2a.5.5 0 0 0 0-1h-2z"/>
                <path fill-rule="evenodd" d="M7.646 15.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 14.293V5.5a.5.5 0 0 0-1 0v8.793l-2.146-2.147a.5.5 0 0 0-.708.708l3 3z"/>
              </svg></a></li>
          </ul>
        </div>
      </nav> 
    </div>
    <div class="container-md">
      {% block content %}
      
      {% endblock content %}
    </div>
    
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}
  Sitema de Gestão Eletronica de Documentos
{% endblock title %}

{% block content%}
<div class="container">
  <div style="float: left; margin: 0; padding: 5px;">
    <div class="card" style="width: 24rem; margin: 10px;">
      <h1 class="card-header", style="text-align: center; height: 150px; margin: 15px;
       padding-top: 55px;">
        {{docs}}
      </h1>
      <div class="card-body">
        <p class="card-text" style="text-align: center;">Total de Documentos Registados</p>
      </div>
    </div>
  </div>
  
  <div style="float: right; margin: 0; padding: 5px;">
    <div class="card" style="width: 24rem; margin: 10px;">
      <h1 class="card-header", style="text-align: center; height: 150px; margin: 15px;
      padding-top: 55px;">{{arquivos}}</h1>
      <div class="card-body">
        <p class="card-text" style="text-align: center;">Total Arquivos</p>
      </div>
    </div>
  </div>
</div>

<div class="container" style="float: bottom; padding-top: 25%;">
  <h3 style="text-align: center;">Ultimos documentos</h3>
</div>
<div class="card card-body border-0 shadow table-wrapper
        table-responsive">
        <table class="table-sm table-hover">
            <thead>
                <tr>
                    <th class="border-gray-200">Nome do documento</th>
                    <th class="border-gray-200">Ficheiro</th>
                    <th class="border-gray-200">Arquivo</th>
                    <th class="border-gray-200">Registado por</th>
                </tr>
            </thead>
            <tbody>
                <!-- Item -->
                {% if docss %}
                {% for do in docss %}
                <tr>
                    <td>
                        <span class="fw-normal">{{do.nome}}</span>
                    </td>
                    <td><span class="fw-normal">{{do.file}}</span></td>
                    <td><span class="fw-normal">{{do.arquivo}}</span></td>
                    <td><span class="fw-normal">{{do.usuario}}</span></td>
                </tr>
                {% endfor %}
                {% else %}
                <td colspan="4" style="text-align: center;"><span class="fw-normal text-warning">Nenhum registo encontrado! </span></td>
                {% endif %}
                
            </tbody>
        </table>
      </div>

{% endblock content %}